# Generated by Django 5.2.6 on 2026-03-25 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=2000)),
                ('referrer', models.CharField(blank=True, default='', max_length=2000)),
                ('user_agent', models.CharField(blank=True, default='', max_length=1000)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_month_hash', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'occurred_at'], name='sa_pv_site_occurred_idx'), models.Index(fields=['occurred_at'], name='sa_pv_occurred_idx')],
            },
        ),
    ]
