# Generated by Django 5.2.6 on 2026-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'date'], name='sa_dailymetric_site_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'date'), name='sa_dailymetric_site_date_unique')],
            },
        ),
    ]
