# Generated by Django 5.2.6 on 2026-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_analytics', '0002_analyticsdailymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMonthlyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('month', models.DateField()),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'month'], name='sa_monthly_site_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'month'), name='sa_monthly_site_month_uniq')],
            },
        ),
    ]
