# Generated by Django 5.2.6 on 2026-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_analytics', '0003_analyticsmonthlymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalyticsSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
