# Generated by Django 5.2.6 on 2025-10-05 04:18

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('github_node_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('default_branch', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='core_repository_owner_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_node_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('github_login', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('zulip_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('zulip_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('github_login'), condition=models.Q(('github_login__isnull', False)), name='core_user_github_login_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='ReviewerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maximum_capacity', models.PositiveIntegerField(default=10)),
                ('auto_assign', models.BooleanField(default=True)),
                ('away_until', models.DateTimeField(blank=True, null=True)),
                ('preferred_labels', models.JSONField(blank=True, default=list)),
                ('free_form', models.TextField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_preferences', to='core.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_preferences', to='core.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'user'), name='core_reviewer_preference_repo_user_unique')],
            },
        ),
    ]
