# Generated by Django 5.2.6 on 2025-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='ci_tracked_checkrun_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='repository',
            name='ci_tracked_status_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
