# Generated by Django 5.2.6 on 2025-11-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository_ci_tracked_checkrun_names_and_more'),
        ('django_celery_results', '0014_alter_taskresult_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResultLink',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='link', serialize=False, to='django_celery_results.taskresult')),
                ('parent_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('root_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['parent_task_id'], name='core_taskre_parent__db4e95_idx'), models.Index(fields=['root_task_id'], name='core_taskre_root_ta_188c22_idx')],
            },
        ),
    ]
