# Generated by Django 5.2.6 on 2025-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskresultlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerpreference',
            name='conflict_of_interest',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
