# Generated by Django 5.2.6 on 2026-02-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_reviewerpreference_conflict_of_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewerpreference",
            name="notification_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="reviewerpreference",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
