# Generated by Django 5.2.6 on 2026-06-18 03:40

import core.services.topic_labels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reviewerpreference_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='assignment_topic_label_pattern',
            field=models.CharField(blank=True, default='', help_text='Case-insensitive regex (full-match) selecting which label names count as reviewer topic labels for auto-assignment and the preferences form. Blank uses the default: t-.*|ci|imo|tech debt|documentation', max_length=500, validators=[core.services.topic_labels.validate_topic_label_pattern]),
        ),
    ]
