# Generated by Django 5.2.6 on 2026-07-09 01:38

from django.db import migrations, models


def backfill_existing_to_auto(apps, schema_editor):
    """Grandfather existing reviewers to the legacy direct-assign behavior.

    The AddField default ("confirm") applies to rows created after this migration; every
    row that already exists at migration time predates the acceptance gate, so it is set to
    "auto" to keep current reviewers' experience unchanged (design doc 050).
    """
    ReviewerPreference = apps.get_model("core", "ReviewerPreference")
    db_alias = schema_editor.connection.alias
    ReviewerPreference.objects.using(db_alias).update(assignment_acceptance="auto")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_repository_assignment_topic_label_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewerpreference",
            name="assignment_acceptance",
            field=models.CharField(choices=[("auto", "auto"), ("confirm", "confirm")], default="confirm", max_length=16),
        ),
        migrations.RunPython(backfill_existing_to_auto, migrations.RunPython.noop),
    ]
