# Generated by Django 5.2.6 on 2026-08-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reviewerpreference_assignment_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerpreference',
            name='max_new_assignments_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
