# Generated by Django 5.2.6 on 2026-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reviewerpreference_max_new_assignments_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerpreference',
            name='excluded_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
