# Generated by Django 5.2.6 on 2025-11-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncer', '0008_pullrequest_commits_earliest_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_sha', models.CharField(max_length=40)),
                ('from_ts', models.DateTimeField()),
                ('to_ts', models.DateTimeField(blank=True, null=True)),
                ('seq', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', '-from_ts', '-seq', 'id'],
                'indexes': [models.Index(fields=['pull_request', 'from_ts'], name='prrev_pr_from_idx'), models.Index(fields=['pull_request', 'head_sha'], name='prrev_pr_sha_idx')],
                'constraints': [models.UniqueConstraint(fields=('pull_request', 'seq'), name='prrev_pr_seq_unique')],
            },
        ),
    ]
