# Generated by Django 5.2.6 on 2025-11-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        ('syncer', '0008_pullrequest_commits_earliest_synced_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prrevision',
            name='prrev_pr_seq_unique',
        ),
        migrations.AddConstraint(
            model_name='prrevision',
            constraint=models.UniqueConstraint(fields=('pull_request', 'from_ts'), name='prrev_pr_from_unique'),
        ),
    ]
