# Generated by Django 5.2.6 on 2025-11-19 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_prrevision_prrev_pr_seq_unique_and_more'),
        ('core', '0002_repository_ci_tracked_checkrun_names_and_more'),
        ('syncer', '0010_alter_pullrequest_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('require_open', models.BooleanField(default=True)),
                ('require_not_draft', models.BooleanField(default=True)),
                ('require_ci_success', models.BooleanField(default=False)),
                ('required_label_names', models.JSONField(blank=True, default=list)),
                ('forbidden_label_names', models.JSONField(blank=True, default=list)),
                ('required_ci_contexts', models.JSONField(blank=True, default=list)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_rule_sets', to='core.repository')),
            ],
            options={
                'ordering': ['repository', '-version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PRQueueWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ts', models.DateTimeField()),
                ('to_ts', models.DateTimeField()),
                ('cycle_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_windows', to='syncer.pullrequest')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_windows', to='analyzer.queueruleset')),
            ],
            options={
                'ordering': ['pull_request', 'rule_set', 'from_ts', 'cycle_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='queueruleset',
            constraint=models.UniqueConstraint(fields=('repository', 'version'), name='analyzer_queueruleset_repo_version_unique'),
        ),
        migrations.AddIndex(
            model_name='prqueuewindow',
            index=models.Index(fields=['pull_request', 'rule_set', 'from_ts'], name='prqwin_pr_ruleset_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='prqueuewindow',
            constraint=models.UniqueConstraint(fields=('pull_request', 'rule_set', 'from_ts'), name='prqwin_pr_ruleset_from_unique'),
        ),
    ]
