# Generated by Django 5.2.6 on 2025-11-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_queueruleset_prqueuewindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueruleset',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueruleset',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
