# Generated by Django 5.2.6 on 2025-11-20 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_queueruleset_effective_from_and_more'),
        ('syncer', '0010_alter_pullrequest_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRRevisionBuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built_through_ts', models.DateTimeField(blank=True, null=True)),
                ('dirty_from_ts', models.DateTimeField(blank=True, null=True)),
                ('builder_version', models.PositiveIntegerField(default=1)),
                ('last_built_at', models.DateTimeField(blank=True, null=True)),
                ('tail_from_ts', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_build_state', to='syncer.pullrequest')),
                ('tail_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_tail_for_state', to='analyzer.prrevision')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['builder_version'], name='prrbs_version_idx'), models.Index(fields=['dirty_from_ts'], name='prrbs_dirty_idx'), models.Index(fields=['built_through_ts'], name='prrbs_built_idx')],
            },
        ),
    ]
