# Generated by Django 5.2.6 on 2025-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_prrevisionbuildstate'),
        ('syncer', '0012_commithistoryharvest_cutoff_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='ci_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='ci_checked_revision_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='revision_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='prrevisionbuildstate',
            index=models.Index(fields=['revision_version'], name='prrbs_rev_version_idx'),
        ),
    ]
