# Generated by Django 5.2.6 on 2025-11-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_prrevisionbuildstate_ci_checked_at_and_more'),
        ('syncer', '0012_commithistoryharvest_cutoff_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='windows_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='windows_built_revision_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='prrevisionbuildstate',
            index=models.Index(fields=['windows_built_revision_version'], name='prrbs_windows_built_rev_idx'),
        ),
    ]
