# Generated by Django 5.2.6 on 2025-11-21 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_prrevisionbuildstate_windows_built_at_and_more'),
        ('core', '0002_repository_ci_tracked_checkrun_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzerConvergenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('pr_no_revisions', models.IntegerField(default=0)),
                ('windows_stale', models.IntegerField(default=0)),
                ('ci_not_checked', models.IntegerField(default=0)),
                ('ci_gated_missing_windows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_convergence_snapshots', to='core.repository')),
            ],
            options={
                'ordering': ['-collected_at', '-id'],
                'indexes': [models.Index(fields=['repository', 'collected_at'], name='an_conv_repo_time_idx')],
            },
        ),
    ]
