# Generated by Django 5.2.6 on 2025-12-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_analyzerconvergencesnapshot'),
        ('core', '0003_taskresultlink'),
        ('syncer', '0015_pullrequest_approvals_pullrequest_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on_number', models.PositiveIntegerField()),
                ('depends_on_pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='syncer.pullrequest')),
                ('depends_on_repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_edges', to='core.repository')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', 'depends_on_repository', 'depends_on_number', 'id'],
                'indexes': [models.Index(fields=['depends_on_repository', 'depends_on_number'], name='prdep_repo_num_idx')],
                'constraints': [models.UniqueConstraint(fields=('pull_request', 'depends_on_repository', 'depends_on_number'), name='analyzer_prdependency_unique_edge')],
            },
        ),
    ]
