# Generated by Django 5.2.6 on 2025-12-04 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_prdependency'),
        ('syncer', '0015_pullrequest_approvals_pullrequest_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDependencyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_body_hash', models.CharField(blank=True, max_length=64)),
                ('builder_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_state', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['last_checked_at'], name='prdepstate_last_checked_idx'), models.Index(fields=['builder_version'], name='prdepstate_builder_version_idx')],
            },
        ),
    ]
