# Generated by Django 5.2.6 on 2025-12-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_prdependencystate'),
        ('core', '0003_taskresultlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(default='default', max_length=128)),
                ('generated_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('etag', models.CharField(max_length=128)),
                ('pr_count', models.PositiveIntegerField()),
                ('queue_count', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_snapshots', to='core.repository')),
            ],
            options={
                'ordering': ['repository', '-generated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'cache_key'), name='analyzer_queuesnapshot_repo_cache_key_unique')],
            },
        ),
    ]
