# Generated by Django 5.2.6 on 2025-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_queuesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerconvergencesnapshot',
            name='prs_missing_dependency_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyzerconvergencesnapshot',
            name='prs_stale_dependency_state',
            field=models.IntegerField(default=0),
        ),
    ]
