# Generated by Django 5.2.6 on 2025-12-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_analyzerconvergencesnapshot_prs_missing_dependency_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueruleset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
