# Generated by Django 5.2.6 on 2025-12-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_reviewerassignmentsnapshot'),
        ('core', '0004_reviewerpreference_conflict_of_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(default='default', max_length=128)),
                ('generated_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('etag', models.CharField(max_length=128)),
                ('area_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('queue_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_stats_snapshots', to='analyzer.queuesnapshot')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_stats_snapshots', to='core.repository')),
            ],
            options={
                'ordering': ['repository', '-generated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('repository', 'cache_key'), name='analyzer_areastatssnapshot_repo_cache_key_unique')],
            },
        ),
    ]
