# Generated by Django 5.2.6 on 2026-01-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_areastatssnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prqueuewindow',
            name='to_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
