# Generated by Django 5.2.6 on 2026-01-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_alter_prqueuewindow_to_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prqueuewindow',
            name='cumulative_seconds_closed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='duration_seconds_closed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='first_on_queue_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='tail_windows',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='window_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
