# Generated by Django 5.2.6 on 2026-01-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_prqueuewindow_cumulative_seconds_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prqueuewindow',
            name='tail_windows',
        ),
    ]
