# Generated by Django 5.2.6 on 2026-01-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_remove_prqueuewindow_tail_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerconvergencesnapshot',
            name='prs_missing_queue_window_rollups',
            field=models.IntegerField(default=0),
        ),
    ]
