# Generated by Django 5.2.6 on 2026-01-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0019_analyzerconvergencesnapshot_prs_missing_queue_window_rollups'),
        ('core', '0004_reviewerpreference_conflict_of_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr_number', models.PositiveIntegerField()),
                ('reviewer_login', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('opted_out_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_opt_outs', to='core.repository')),
            ],
            options={
                'ordering': ['repository', '-opted_out_at', 'id'],
                'indexes': [models.Index(fields=['repository', 'pr_number', 'active'], name='an_roo_pr_active_idx'), models.Index(fields=['repository', 'reviewer_login', 'active'], name='an_roo_reviewer_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'pr_number', 'reviewer_login'), name='analyzer_revieweroptout_repo_pr_reviewer_unique')],
            },
        ),
    ]
