# Generated by Django 5.2.6 on 2026-02-28 01:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0020_revieweroptout"),
        ("core", "0005_reviewerpreference_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewerAttentionDailyRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_date", models.DateField(db_index=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="started", max_length=24)),
                ("reports_enabled", models.BooleanField(default=False)),
                ("enforcement_enabled", models.BooleanField(default=False)),
                ("delivery_enabled", models.BooleanField(default=False)),
                ("task_id", models.CharField(blank=True, default="", max_length=255)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer_attention_daily_runs",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewerAttentionAutoUnassignRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_date", models.DateField()),
                ("pr_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("unassigned", "Unassigned"),
                            ("failed", "Failed"),
                            ("skipped_no_token", "Skipped (no token)"),
                            ("skipped_disabled", "Skipped (disabled)"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_attention_auto_unassign_records",
                        to="core.repository",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_attention_auto_unassign_records",
                        to="core.user",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_unassign_records",
                        to="analyzer.reviewerattentiondailyrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewerAttentionNotificationRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_date", models.DateField()),
                ("pr_number", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("new_assignment", "New assignment"),
                            ("nudge", "Queue nudge"),
                            ("auto_unassign", "Auto-unassign threshold"),
                        ],
                        max_length=24,
                    ),
                ),
                ("cycle_anchor_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=16
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_attention_notification_records",
                        to="core.repository",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_attention_notification_records",
                        to="core.user",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_records",
                        to="analyzer.reviewerattentiondailyrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reviewerattentiondailyrun",
            index=models.Index(fields=["run_date", "status"], name="an_ra_run_date_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewerattentionautounassignrecord",
            index=models.Index(fields=["run_date", "status"], name="an_ra_unassign_day_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewerattentionautounassignrecord",
            index=models.Index(fields=["reviewer", "run_date"], name="an_ra_unassign_user_day_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewerattentionautounassignrecord",
            constraint=models.UniqueConstraint(
                fields=("run_date", "repository", "reviewer", "pr_number"), name="an_ra_unassign_day_repo_user_pr_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewerattentionnotificationrecord",
            index=models.Index(fields=["run_date", "status"], name="an_ra_notify_day_status_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewerattentionnotificationrecord",
            index=models.Index(fields=["reviewer", "run_date"], name="an_ra_notify_user_day_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewerattentionnotificationrecord",
            constraint=models.UniqueConstraint(
                fields=("repository", "reviewer", "pr_number", "category", "cycle_anchor_at"),
                name="an_ra_notify_repo_user_pr_cat_anchor_uniq",
            ),
        ),
    ]
