# Generated by Django 5.2.6 on 2026-03-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0021_reviewerattentiondailyrun_and_more'),
        ('syncer', '0029_syncerconvergencesnapshot_discovery_continuation_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRQueueWindowBuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_version_built', models.PositiveIntegerField(blank=True, null=True)),
                ('windows_built_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_window_build_states', to='syncer.pullrequest')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_window_build_states', to='analyzer.queueruleset')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['pull_request'], name='prqwbs_pr_idx'), models.Index(fields=['rule_set'], name='prqwbs_ruleset_idx'), models.Index(fields=['revision_version_built'], name='prqwbs_rev_built_idx')],
                'constraints': [models.UniqueConstraint(fields=('pull_request', 'rule_set'), name='prqwbs_pr_ruleset_unique')],
            },
        ),
    ]
