# Generated by Django 5.2.6 on 2026-03-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0022_prqueuewindowbuildstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueruleset",
            name="ci_gating_mode",
            field=models.CharField(
                choices=[
                    ("all_required_success", "All required contexts must succeed"),
                    ("no_required_failures", "Only required-context failures block queue entry"),
                ],
                default="all_required_success",
                max_length=64,
            ),
        ),
    ]
