# Generated by Django 5.2.6 on 2026-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0023_queueruleset_ci_gating_mode'),
        ('core', '0005_reviewerpreference_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueruleset',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='queueruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('repository',), name='analyzer_queueruleset_repo_single_default'),
        ),
    ]
