# Generated by Django 5.2.6 on 2026-04-04 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0024_add_queueruleset_is_default'),
        ('syncer', '0038_repodiscoverystate_continuation_success_cutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prqueuewindow',
            name='closed_at_head_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='closed_by_check_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.commitcheckrun'),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='closed_by_event_type',
            field=models.CharField(blank=True, choices=[('REQUIRED_LABEL_ADDED', 'required_label_added'), ('REQUIRED_LABEL_REMOVED', 'required_label_removed'), ('FORBIDDEN_LABEL_ADDED', 'forbidden_label_added'), ('FORBIDDEN_LABEL_REMOVED', 'forbidden_label_removed'), ('CI_PASSED', 'ci_passed'), ('CI_FAILED', 'ci_failed'), ('PR_OPENED', 'pr_opened'), ('DRAFT_CONVERTED', 'draft_converted'), ('CONVERTED_TO_DRAFT', 'converted_to_draft'), ('PR_CLOSED', 'pr_closed'), ('HEAD_PUSHED', 'head_pushed'), ('INITIAL_STATE', 'initial_state'), ('RULESET_EFFECTIVE', 'ruleset_effective'), ('UNKNOWN', 'unknown')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='closed_by_status_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.commitstatuscontext'),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='closed_by_timeline_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.prtimelineevent'),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='opened_at_head_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='opened_by_check_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.commitcheckrun'),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='opened_by_event_type',
            field=models.CharField(blank=True, choices=[('REQUIRED_LABEL_ADDED', 'required_label_added'), ('REQUIRED_LABEL_REMOVED', 'required_label_removed'), ('FORBIDDEN_LABEL_ADDED', 'forbidden_label_added'), ('FORBIDDEN_LABEL_REMOVED', 'forbidden_label_removed'), ('CI_PASSED', 'ci_passed'), ('CI_FAILED', 'ci_failed'), ('PR_OPENED', 'pr_opened'), ('DRAFT_CONVERTED', 'draft_converted'), ('CONVERTED_TO_DRAFT', 'converted_to_draft'), ('PR_CLOSED', 'pr_closed'), ('HEAD_PUSHED', 'head_pushed'), ('INITIAL_STATE', 'initial_state'), ('RULESET_EFFECTIVE', 'ruleset_effective'), ('UNKNOWN', 'unknown')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='opened_by_status_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.commitstatuscontext'),
        ),
        migrations.AddField(
            model_name='prqueuewindow',
            name='opened_by_timeline_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='syncer.prtimelineevent'),
        ),
    ]
