# Generated by Django 5.2.6 on 2026-04-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0025_prqueuewindow_closed_at_head_sha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzerconvergencesnapshot',
            name='windows_unknown_attribution',
            field=models.IntegerField(default=0),
        ),
    ]
