# Generated by Django 5.2.6 on 2026-05-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0026_analyzerconvergencesnapshot_windows_unknown_attribution'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prrevisionbuildstate',
            name='prrbs_windows_built_rev_idx',
        ),
        migrations.RemoveField(
            model_name='prrevisionbuildstate',
            name='windows_built_at',
        ),
        migrations.RemoveField(
            model_name='prrevisionbuildstate',
            name='windows_built_revision_version',
        ),
    ]
