# Generated by Django 5.2.6 on 2026-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0027_drop_legacy_windows_built_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prrevisionbuildstate',
            name='latest_ci_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
