# Generated by Django 5.2.6 on 2026-06-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0028_add_latest_ci_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueruleset',
            name='assignment_forbidden_label_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
