# Generated by Django 5.2.6 on 2026-06-22 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0029_queueruleset_assignment_forbidden_label_names'),
        ('core', '0006_repository_assignment_topic_label_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_date', models.DateField(db_index=True)),
                ('pr_number', models.PositiveIntegerField()),
                ('reviewer_login', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('skipped_already_assigned', 'Skipped (already assigned)'), ('skipped_opted_out', 'Skipped (opted out)'), ('skipped_ineligible', 'Skipped (reviewer ineligible)'), ('skipped_recently_applied', 'Skipped (recently applied)'), ('skipped_no_token', 'Skipped (no token)'), ('skipped_disabled', 'Skipped (disabled)'), ('skipped_dry_run', 'Skipped (dry run)')], default='pending', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_assignment_applications', to='core.repository')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='analyzer.reviewerassignmentsnapshot')),
            ],
            options={
                'ordering': ['-run_date', 'repository', 'pr_number', 'id'],
                'indexes': [models.Index(fields=['repository', 'pr_number', 'reviewer_login', 'status'], name='an_raa_repo_pr_rev_status_idx'), models.Index(fields=['run_date', 'status'], name='an_raa_day_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('run_date', 'repository', 'pr_number', 'reviewer_login'), name='an_raa_day_repo_pr_reviewer_uniq')],
            },
        ),
    ]
