# Generated by Django 5.2.6 on 2026-07-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0030_reviewerassignmentapplication"),
        ("core", "0007_reviewerpreference_assignment_acceptance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pr_number", models.PositiveIntegerField()),
                ("reviewer_login", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        default="proposed",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_via",
                    models.CharField(
                        blank=True,
                        choices=[("console", "Console"), ("auto_expire", "Auto-expire"), ("sync_superseded", "Sync superseded")],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignment_proposals", to="core.repository"
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="analyzer.reviewerassignmentsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["repository", "pr_number", "-id"],
                "indexes": [
                    models.Index(fields=["repository", "reviewer_login", "state", "decided_at"], name="an_ap_reviewer_state_idx"),
                    models.Index(fields=["repository", "pr_number", "state"], name="an_ap_pr_state_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "proposed")),
                        fields=("repository", "pr_number"),
                        name="an_ap_one_active_proposal_per_pr",
                    )
                ],
            },
        ),
    ]
