# Generated by Django 5.2.6 on 2026-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0031_assignmentproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerassignmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed'), ('skipped_already_assigned', 'Skipped (already assigned)'), ('skipped_opted_out', 'Skipped (opted out)'), ('skipped_excluded_label', 'Skipped (excluded label)'), ('skipped_ineligible', 'Skipped (reviewer ineligible)'), ('skipped_recently_applied', 'Skipped (recently applied)'), ('skipped_no_token', 'Skipped (no token)'), ('skipped_disabled', 'Skipped (disabled)'), ('skipped_dry_run', 'Skipped (dry run)')], default='pending', max_length=32),
        ),
    ]
