# Generated by Django 5.2.6 on 2025-10-09 15:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_defs', to='core.repository')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=10)),
                ('is_draft', models.BooleanField(default=False)),
                ('gh_created_at', models.DateTimeField()),
                ('gh_updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('base_ref_name', models.CharField(max_length=255)),
                ('head_ref_name', models.CharField(max_length=255)),
                ('head_repo_owner_login', models.CharField(max_length=255)),
                ('head_repo_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
                ('changed_files_count', models.IntegerField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='core.user')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.repository')),
            ],
        ),
        migrations.CreateModel(
            name='PRTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('LABELED', 'labeled'), ('UNLABELED', 'unlabeled'), ('READY_FOR_REVIEW', 'ready_for_review'), ('CONVERT_TO_DRAFT', 'convert_to_draft'), ('REOPENED', 'reopened'), ('CLOSED', 'closed')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('label_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', 'occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PRLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to', to='syncer.labeldef')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='syncer.pullrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_node_id', models.CharField(max_length=255, unique=True)),
                ('head_sha', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'queued'), ('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed')], max_length=20)),
                ('conclusion', models.CharField(blank=True, choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('CANCELLED', 'cancelled'), ('NEUTRAL', 'neutral'), ('SKIPPED', 'skipped'), ('TIMED_OUT', 'timed_out'), ('ACTION_REQUIRED', 'action_required')], max_length=20, null=True)),
                ('details_url', models.URLField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gh_started_at', models.DateTimeField(blank=True, null=True)),
                ('gh_completed_at', models.DateTimeField(blank=True, null=True)),
                ('gh_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', 'gh_completed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatusContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rest_id', models.BigIntegerField(unique=True)),
                ('head_sha', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ERROR', 'error'), ('PENDING', 'pending')], max_length=20)),
                ('target_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gh_created_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_contexts', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', 'gh_created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='labeldef',
            constraint=models.UniqueConstraint(models.F('repository'), django.db.models.functions.text.Lower('name'), name='syncer_labeldef_repo_lower_name_unique'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', 'state'], name='syncer_pr_repo_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['repository', 'gh_updated_at'], name='syncer_pr_repo_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('repository', 'number'), name='syncer_pullrequest_repo_number_unique'),
        ),
        migrations.AddIndex(
            model_name='prtimelineevent',
            index=models.Index(fields=['pull_request', 'occurred_at'], name='syncer_prtimeline_pr_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='prtimelineevent',
            constraint=models.UniqueConstraint(condition=models.Q(('github_node_id__isnull', False)), fields=('github_node_id',), name='syncer_prtimelineevent_node_id_unique'),
        ),
        migrations.AddIndex(
            model_name='prlabel',
            index=models.Index(fields=['pull_request'], name='syncer_prlabel_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='prlabel',
            index=models.Index(fields=['label_def'], name='syncer_prlabel_label_idx'),
        ),
        migrations.AddConstraint(
            model_name='prlabel',
            constraint=models.UniqueConstraint(fields=('pull_request', 'label_def'), name='syncer_prlabel_pr_label_unique'),
        ),
        migrations.AddIndex(
            model_name='checkrun',
            index=models.Index(fields=['pull_request', 'gh_completed_at'], name='ckrun_pr_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='statuscontext',
            index=models.Index(fields=['pull_request', 'gh_created_at'], name='stctx_pr_created_idx'),
        ),
    ]
