# Generated by Django 5.2.6 on 2025-10-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscontext',
            name='github_node_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statuscontext',
            name='rest_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='statuscontext',
            constraint=models.UniqueConstraint(condition=models.Q(('github_node_id__isnull', False)), fields=('github_node_id',), name='stctx_nodeid_uniq'),
        ),
        migrations.AddConstraint(
            model_name='statuscontext',
            constraint=models.UniqueConstraint(condition=models.Q(('rest_id__isnull', False)), fields=('rest_id',), name='stctx_restid_uniq'),
        ),
    ]
