# Generated by Django 5.2.6 on 2025-10-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0002_statuscontext_github_node_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkrun',
            name='gh_updated_at',
        ),
    ]
