# Generated by Django 5.2.6 on 2025-11-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0003_remove_checkrun_gh_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prtimelineevent',
            name='after_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='prtimelineevent',
            name='before_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='prtimelineevent',
            name='type',
            field=models.CharField(choices=[('LABELED', 'labeled'), ('UNLABELED', 'unlabeled'), ('READY_FOR_REVIEW', 'ready_for_review'), ('CONVERT_TO_DRAFT', 'convert_to_draft'), ('REOPENED', 'reopened'), ('CLOSED', 'closed'), ('HEAD_FORCE_PUSHED', 'head_force_pushed')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='prtimelineevent',
            index=models.Index(condition=models.Q(('after_sha__isnull', False), ('type', 'HEAD_FORCE_PUSHED')), fields=['pull_request', 'after_sha'], name='syncer_prtl_aftersha_idx'),
        ),
        migrations.AddConstraint(
            model_name='prtimelineevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'HEAD_FORCE_PUSHED'), ('before_sha__isnull', False), ('after_sha__isnull', False)), models.Q(models.Q(('type', 'HEAD_FORCE_PUSHED'), _negated=True), ('before_sha__isnull', True), ('after_sha__isnull', True)), _connector='OR'), name='syncer_prtl_sha_by_type_ck'),
        ),
        migrations.AddConstraint(
            model_name='prtimelineevent',
            constraint=models.CheckConstraint(condition=models.Q(('label_name__isnull', True), ('type__in', ['LABELED', 'UNLABELED']), _connector='OR'), name='syncer_prtl_label_by_type_ck'),
        ),
    ]
