# Generated by Django 5.2.6 on 2025-11-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0005_syncermetricssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='timeline_backfill_cursor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='timeline_backfill_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='timeline_earliest_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
