# Generated by Django 5.2.6 on 2025-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0006_pullrequest_timeline_backfill_cursor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='commits_backfill_cursor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='commits_backfill_done',
            field=models.BooleanField(default=False),
        ),
    ]
