# Generated by Django 5.2.6 on 2025-11-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0007_pullrequest_commits_backfill_cursor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='commits_earliest_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
