# Generated by Django 5.2.6 on 2025-11-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('syncer', '0008_pullrequest_commits_earliest_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoBackfillCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_cursor', models.TextField(blank=True, null=True)),
                ('oldest_created_at', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_cursor', to='core.repository')),
            ],
            options={
                'verbose_name': 'Repository backfill cursor',
                'verbose_name_plural': 'Repository backfill cursors',
            },
        ),
    ]
