# Generated by Django 5.2.6 on 2025-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0009_repobackfillcursor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='state',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('merged', 'merged')], max_length=10),
        ),
    ]
