# Generated by Django 5.2.6 on 2025-11-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0010_alter_pullrequest_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitHistoryHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sha', models.CharField(max_length=40)),
                ('cursor', models.TextField(blank=True, null=True)),
                ('has_more', models.BooleanField(default=True)),
                ('last_harvested_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_history_harvests', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['pull_request', 'start_sha'], name='chh_pr_sha_idx'), models.Index(fields=['has_more'], name='chh_has_more_idx')],
                'unique_together': {('pull_request', 'start_sha')},
            },
        ),
    ]
