# Generated by Django 5.2.6 on 2025-11-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0011_commithistoryharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='commithistoryharvest',
            name='cutoff_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
