# Generated by Django 5.2.6 on 2025-11-21 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository_ci_tracked_checkrun_names_and_more'),
        ('syncer', '0012_commithistoryharvest_cutoff_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncerConvergenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(db_index=True)),
                ('timeline_backfill_pending', models.IntegerField(default=0)),
                ('commits_backfill_pending', models.IntegerField(default=0)),
                ('incomplete_prs', models.IntegerField(default=0)),
                ('harvest_jobs_open', models.IntegerField(default=0)),
                ('history_cursor_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncer_convergence_snapshots', to='core.repository')),
            ],
            options={
                'ordering': ['-collected_at', '-id'],
                'indexes': [models.Index(fields=['repository', 'collected_at'], name='sync_conv_repo_time_idx')],
            },
        ),
    ]
