# Generated by Django 5.2.6 on 2025-11-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0013_syncerconvergencesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='queue_default_depth',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='queue_github_depth',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
