# Generated by Django 5.2.6 on 2025-12-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0014_syncermetricssnapshot_queue_default_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='approvals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='assignees',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='assignees_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='commenters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='comments_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='engagement_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='files',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='files_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='number_total_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='reviews_incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
