# Generated by Django 5.2.6 on 2025-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0015_pullrequest_approvals_pullrequest_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_engagement_incomplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_commits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_engagement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_timeline',
            field=models.IntegerField(default=0),
        ),
    ]
