# Generated by Django 5.2.6 on 2025-12-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0016_syncerconvergencesnapshot_prs_engagement_incomplete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_commits',
        ),
        migrations.RemoveField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_timeline',
        ),
    ]
