# Generated by Django 5.2.6 on 2025-12-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0017_remove_syncerconvergencesnapshot_prs_missing_commits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='head_ci_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
