# Generated by Django 5.2.6 on 2025-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0018_pullrequest_head_ci_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_head_ci_state',
            field=models.IntegerField(default=0),
        ),
    ]
