# Generated by Django 5.2.6 on 2025-12-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0019_syncerconvergencesnapshot_prs_missing_head_ci_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='token_cost_total',
            field=models.IntegerField(default=0),
        ),
    ]
