# Generated by Django 5.2.6 on 2026-01-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0020_syncermetricssnapshot_token_cost_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='head_sha',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
