# Generated by Django 5.2.6 on 2026-01-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0021_pullrequest_head_sha'),
        ('syncer', '0022_syncerconvergencesnapshot_prs_missing_head_sha'),
    ]

    operations = [
    ]
