# Generated by Django 5.2.6 on 2026-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0023_merge_20260109_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_head_ci_contexts',
            field=models.IntegerField(default=0),
        ),
    ]
