# Generated by Django 5.2.6 on 2026-01-30 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reviewerpreference_conflict_of_interest'),
        ('syncer', '0024_syncerconvergencesnapshot_prs_missing_head_ci_contexts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIShaFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha', models.CharField(db_index=True, max_length=64)),
                ('last_attempted_at', models.DateTimeField()),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repository')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('repository', 'sha'), name='syncer_cishafetchstate_repo_sha_uniq')],
            },
        ),
    ]
