# Generated by Django 5.2.6 on 2026-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0025_cishafetchstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prtimelineevent',
            name='actor_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prtimelineevent',
            name='assignee_login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prtimelineevent',
            name='type',
            field=models.CharField(choices=[('LABELED', 'labeled'), ('UNLABELED', 'unlabeled'), ('ASSIGNED', 'assigned'), ('UNASSIGNED', 'unassigned'), ('READY_FOR_REVIEW', 'ready_for_review'), ('CONVERT_TO_DRAFT', 'convert_to_draft'), ('REOPENED', 'reopened'), ('CLOSED', 'closed'), ('HEAD_FORCE_PUSHED', 'head_force_pushed')], max_length=32),
        ),
    ]
