# Generated by Django 5.2.6 on 2026-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0026_prtimelineevent_actor_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='last_assignment_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
