# Generated by Django 5.2.6 on 2026-02-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reviewerpreference_notifications'),
        ('syncer', '0027_pullrequest_last_assignment_event_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDiscoveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_successful_cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('continuation_cutoff_at', models.DateTimeField(blank=True, null=True)),
                ('continuation_cursor', models.TextField(blank=True, null=True)),
                ('continuation_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_state', to='core.repository')),
            ],
            options={
                'verbose_name': 'Repository discovery state',
                'verbose_name_plural': 'Repository discovery states',
            },
        ),
    ]
