# Generated by Django 5.2.6 on 2026-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0028_repodiscoverystate"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="discovery_continuation_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="discovery_lag_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="discovery_last_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="discovery_last_successful_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
