# Generated by Django 5.2.6 on 2026-03-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_reviewerpreference_notifications"),
        ("syncer", "0029_syncerconvergencesnapshot_discovery_continuation_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitCheckRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_node_id", models.CharField(blank=True, max_length=255, null=True)),
                ("head_sha", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("QUEUED", "queued"), ("IN_PROGRESS", "in_progress"), ("COMPLETED", "completed")], max_length=20
                    ),
                ),
                (
                    "conclusion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESS", "success"),
                            ("FAILURE", "failure"),
                            ("CANCELLED", "cancelled"),
                            ("NEUTRAL", "neutral"),
                            ("SKIPPED", "skipped"),
                            ("TIMED_OUT", "timed_out"),
                            ("ACTION_REQUIRED", "action_required"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("details_url", models.URLField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("gh_started_at", models.DateTimeField(blank=True, null=True)),
                ("gh_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commit_check_runs", to="core.repository"
                    ),
                ),
            ],
            options={
                "ordering": ["repository", "head_sha", "gh_completed_at", "id"],
                "indexes": [
                    models.Index(fields=["repository", "head_sha"], name="cckr_repo_sha_idx"),
                    models.Index(fields=["repository", "gh_completed_at"], name="cckr_repo_comp_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("github_node_id__isnull", False)), fields=("github_node_id",), name="cckr_nodeid_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("external_id__isnull", False)),
                        fields=("repository", "head_sha", "name", "external_id"),
                        name="cckr_repo_sha_name_ext_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommitStatusContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("github_node_id", models.CharField(blank=True, max_length=255, null=True)),
                ("rest_id", models.BigIntegerField(blank=True, null=True)),
                ("head_sha", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[("SUCCESS", "success"), ("FAILURE", "failure"), ("ERROR", "error"), ("PENDING", "pending")],
                        max_length=20,
                    ),
                ),
                ("target_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("gh_created_at", models.DateTimeField()),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commit_status_contexts", to="core.repository"
                    ),
                ),
            ],
            options={
                "ordering": ["repository", "head_sha", "gh_created_at", "id"],
                "indexes": [
                    models.Index(fields=["repository", "head_sha"], name="cscx_repo_sha_idx"),
                    models.Index(fields=["repository", "gh_created_at"], name="cscx_repo_crtd_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("github_node_id__isnull", False)), fields=("github_node_id",), name="cscx_nodeid_uniq"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("rest_id__isnull", False)), fields=("rest_id",), name="cscx_restid_uniq"
                    ),
                ],
            },
        ),
    ]
