# Generated by Django 5.2.6 on 2026-03-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0030_commitcheckrun_commitstatuscontext"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("action", models.CharField(blank=True, default="", max_length=100)),
                ("repository_owner", models.CharField(blank=True, default="", max_length=255)),
                ("repository_name", models.CharField(blank=True, default="", max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("ACCEPTED", "accepted")], max_length=32)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-received_at", "-id"],
                "indexes": [
                    models.Index(fields=["event_type", "received_at"], name="ghw_event_recv_idx"),
                    models.Index(fields=["repository_owner", "repository_name"], name="ghw_repo_idx"),
                ],
            },
        ),
    ]
