# Generated by Django 5.2.6 on 2026-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0031_githubwebhookdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_deliveries",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_reason_enqueued_sync_ci",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_reason_enqueued_sync_pr",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_reason_ignored_action",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_route_check",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_route_noop",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_route_pull_request",
            field=models.IntegerField(default=0),
        ),
    ]
