# Generated by Django 5.2.6 on 2026-03-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0032_syncermetricssnapshot_webhook_deliveries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="duplicate_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="githubwebhookdelivery",
            name="last_duplicate_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_duplicates_touched",
            field=models.IntegerField(default=0),
        ),
    ]
