# Generated by Django 5.2.6 on 2026-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0033_githubwebhookdelivery_duplicate_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_deduped_sync_ci_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_reason_deduped_sync_ci",
            field=models.IntegerField(default=0),
        ),
    ]
