# Generated by Django 5.2.6 on 2026-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0034_syncermetricssnapshot_webhook_deduped_sync_ci_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_deduped_sync_pr_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncermetricssnapshot",
            name="webhook_reason_deduped_sync_pr",
            field=models.IntegerField(default=0),
        ),
    ]
