# Generated by Django 5.2.6 on 2026-03-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0035_syncermetricssnapshot_webhook_deduped_sync_pr_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='sha_task_impacted_pr_fanout_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='webhook_check_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncermetricssnapshot',
            name='webhook_sha_first_tasks_enqueued',
            field=models.IntegerField(default=0),
        ),
    ]
