# Generated by Django 5.2.6 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0037_remove_legacy_pr_ci_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="repodiscoverystate",
            name="continuation_success_cutoff",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="discovery_catchup_lag_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
