# Generated by Django 5.2.6 on 2026-05-08 00:47

from django.db import migrations, models


def stamp_engagement_synced_prs_to_v1(apps, schema_editor):
    """Backfill sync_schema_version=1 for PRs whose engagement fields are already synced.

    See docs/design-decisions/044-sync-schema-versioning-and-comment-review-timeline-events.md.
    The previous bookkeeping column ``engagement_synced_at`` is being replaced by
    ``sync_schema_version``; PRs that completed the v1 (engagement-fields)
    expansion under the old column should land at the new column's matching value
    so the upgrader doesn't redundantly re-kick them.
    """
    PullRequest = apps.get_model("syncer", "PullRequest")
    PullRequest.objects.filter(engagement_synced_at__isnull=False).update(sync_schema_version=1)


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0038_repodiscoverystate_continuation_success_cutoff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prtimelineevent",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="prtimelineevent",
            name="inline_comment_total_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prtimelineevent",
            name="requested_reviewer_login",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prtimelineevent",
            name="requested_team_slug",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="sync_schema_version",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(
            stamp_engagement_synced_prs_to_v1,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
