# Generated by Django 5.2.6 on 2026-05-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0039_prtimelineevent_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='prs_below_current_sync_schema_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='sync_schema_version_target',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
