# Generated by Django 5.2.6 on 2026-05-08 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0040_syncerconvergencesnapshot_prs_below_current_sync_schema_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRReviewInlineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_node_id', models.CharField(max_length=255, unique=True)),
                ('review_node_id', models.CharField(db_index=True, max_length=255)),
                ('author_login', models.CharField(blank=True, max_length=255)),
                ('gh_created_at', models.DateTimeField()),
                ('path', models.CharField(max_length=512)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('original_line', models.IntegerField(blank=True, null=True)),
                ('reply_to_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_root_node_id', models.CharField(db_index=True, max_length=255)),
                ('parent_review_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inline_comments', to='syncer.prtimelineevent')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_inline_comments', to='syncer.pullrequest')),
            ],
            options={
                'ordering': ['pull_request', 'gh_created_at', 'id'],
                'indexes': [models.Index(fields=['pull_request', 'gh_created_at'], name='syncer_prric_pr_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='PRReviewInlineCommentBackfill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inline_comment_backfill', serialize=False, to='syncer.prtimelineevent')),
                ('review_node_id', models.CharField(db_index=True, max_length=255)),
                ('total_count', models.IntegerField()),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_inline_comment_backfills', to='syncer.pullrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['pull_request'], name='syncer_prricbf_pr_idx')],
            },
        ),
    ]
