# Generated by Django 5.2.6 on 2026-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0041_prreviewinlinecomment_prreviewinlinecommentbackfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prtimelineevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("LABELED", "labeled"),
                    ("UNLABELED", "unlabeled"),
                    ("ASSIGNED", "assigned"),
                    ("UNASSIGNED", "unassigned"),
                    ("READY_FOR_REVIEW", "ready_for_review"),
                    ("CONVERT_TO_DRAFT", "convert_to_draft"),
                    ("REOPENED", "reopened"),
                    ("CLOSED", "closed"),
                    ("HEAD_FORCE_PUSHED", "head_force_pushed"),
                    ("ISSUE_COMMENTED", "issue_commented"),
                    ("REVIEW_APPROVED", "review_approved"),
                    ("REVIEW_CHANGES_REQUESTED", "review_changes_requested"),
                    ("REVIEW_COMMENTED", "review_commented"),
                    ("REVIEW_DISMISSED", "review_dismissed"),
                    ("REVIEW_REQUESTED", "review_requested"),
                    ("REVIEW_REQUEST_REMOVED", "review_request_removed"),
                ],
                max_length=32,
            ),
        ),
    ]
