# Generated by Django 5.2.6 on 2026-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0042_alter_prtimelineevent_type"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="prtimelineevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("requested_reviewer_login__isnull", True), ("requested_team_slug__isnull", True)),
                    ("type__in", ["REVIEW_REQUESTED", "REVIEW_REQUEST_REMOVED"]),
                    _connector="OR",
                ),
                name="syncer_prtl_requested_reviewer_by_type_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="prtimelineevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("requested_reviewer_login__isnull", True), ("requested_team_slug__isnull", True), _connector="OR"
                ),
                name="syncer_prtl_requested_reviewer_mutex_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="prtimelineevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inline_comment_total_count__isnull", True),
                    ("type__in", ["REVIEW_APPROVED", "REVIEW_CHANGES_REQUESTED", "REVIEW_COMMENTED"]),
                    _connector="OR",
                ),
                name="syncer_prtl_inline_total_by_type_ck",
            ),
        ),
    ]
