# Generated by Django 5.2.6 on 2026-05-08 13:28
#
# Beyond the auto-generated schema changes, this migration:
#
# 1. Replaces the primary key on PRReviewInlineCommentBackfill — the old
#    schema used ``review_event`` (OneToOneField, primary_key=True) as the
#    PK; the new schema uses an auto ``id`` so ``review_event`` can be
#    nullable (covers dismissed reviews whose dismiss event had
#    ``review: null`` on GitHub, blocking synthesis). Auto-generated
#    Django ops would have run ``AddField id (primary_key=True)`` BEFORE
#    ``AlterField review_event (drop primary_key=True)``, which Postgres
#    rejects ("multiple primary keys for table"). Wrapping the PK swap
#    in ``SeparateDatabaseAndState`` lets us drop the old PK + add the
#    new id column + make review_event nullable in one raw-SQL phase,
#    while keeping Django's model-state bookkeeping correct.
#
# 2. Adds a unique constraint on ``review_node_id`` (the new durable key),
#    a CHECK on ``PRReviewInlineComment.review_node_id != ''`` (defends
#    against accidental orphan rows), and an index on
#    ``PRReviewInlineComment.reply_to_node_id`` (supports the new
#    DB-aware thread-root lookup).
#
# 3. Backfills the data shape established by design doc 044 §Item 1
#    (synthesis): for every existing REVIEW_DISMISSED row whose extra
#    carries a dismissed_review_node_id + previous_review_state +
#    dismissed_review_submitted_at, INSERT a synthesized
#    REVIEW_<previous_review_state> row keyed on the dismissed review's
#    github_node_id (skipping when one already exists). Without this,
#    PRs synced for the first time AFTER a review's dismissal (Case B)
#    would keep their inconsistent data shape until rewalked, while PRs
#    synced before the dismissal (Case A) would already be correct.
#
# 4. Repairs PRReviewInlineComment.parent_review_event_id for any rows
#    whose parent timeline event now exists (after step 3, or because
#    the comment was ingested before its parent for unrelated reasons).
#
# Steps 3 and 4 run as bulk SQL: the row counts are bounded by the
# population of REVIEW_DISMISSED rows (small) and the population of
# inline comments with NULL parent FK (also small in practice).

import django.db.models.deletion
from django.db import migrations, models


def _synthesize_dismissed_review_parents(apps, schema_editor):
    """Insert REVIEW_<previousReviewState> rows for existing dismiss events.

    Uses raw SQL so the work is one bulk INSERT...SELECT regardless of how
    many REVIEW_DISMISSED rows exist. The ``NOT EXISTS`` filter guards
    against pre-existing parent rows (Case A).

    We deliberately avoid ``ON CONFLICT ON CONSTRAINT
    syncer_prtimelineevent_node_id_unique DO NOTHING`` here: that name
    refers to a *partial unique index* (Django's ``UniqueConstraint`` with
    a ``condition=`` becomes a partial index in Postgres, not a named
    constraint), and constraint-name conflict targets don't apply to
    indexes. ``ON CONFLICT (github_node_id) WHERE github_node_id IS NOT
    NULL DO NOTHING`` would also work, but the explicit anti-join makes
    the intent clear at a glance and doesn't depend on knowing the
    partial-index predicate. The migration is single-threaded so the
    classic NOT EXISTS race window doesn't matter here.
    """
    schema_editor.execute("""
        INSERT INTO syncer_prtimelineevent (
            pull_request_id,
            github_node_id,
            type,
            occurred_at,
            actor_login,
            extra,
            created_at,
            updated_at
        )
        SELECT
            d.pull_request_id,
            d.extra->>'dismissed_review_node_id',
            'REVIEW_' || (d.extra->>'previous_review_state'),
            (d.extra->>'dismissed_review_submitted_at')::timestamptz,
            -- actor_login: empty string when missing/null, matching the
            -- live code's _synthesize_dismissed_review_parent path which
            -- uses ``dismiss_extra.get("dismissed_review_author") or ""``.
            -- Aligning the two paths keeps the data shape identical
            -- regardless of whether the row was backfilled by this
            -- migration or synthesized at ingest time.
            COALESCE(d.extra->>'dismissed_review_author', ''),
            '{}'::jsonb,
            NOW(),
            NOW()
        FROM syncer_prtimelineevent d
        WHERE d.type = 'REVIEW_DISMISSED'
          AND d.extra ? 'dismissed_review_node_id'
          AND d.extra ? 'previous_review_state'
          AND d.extra ? 'dismissed_review_submitted_at'
          AND (d.extra->>'dismissed_review_node_id') IS NOT NULL
          AND (d.extra->>'dismissed_review_submitted_at') IS NOT NULL
          AND (d.extra->>'previous_review_state') IN ('APPROVED', 'CHANGES_REQUESTED', 'COMMENTED')
          AND NOT EXISTS (
            SELECT 1
              FROM syncer_prtimelineevent existing
             WHERE existing.github_node_id = d.extra->>'dismissed_review_node_id'
          );
    """)


def _link_inline_comments_to_synthesized_parents(apps, schema_editor):
    """Set parent_review_event_id on inline comments whose parent now exists.

    After step 3, dismissed-review inline comments that had been ingested
    with parent_review_event=NULL can now point at the newly-synthesized
    REVIEW_<state> row. This also picks up any other inline comments
    whose parent row has been reconstituted for unrelated reasons.
    """
    schema_editor.execute("""
        UPDATE syncer_prreviewinlinecomment ic
           SET parent_review_event_id = ev.id
          FROM syncer_prtimelineevent ev
         WHERE ic.parent_review_event_id IS NULL
           AND ic.review_node_id <> ''
           AND ev.github_node_id = ic.review_node_id;
    """)


def _noop_reverse(apps, schema_editor):
    """Forward-only data backfill.

    Reversing would require remembering which rows we created vs. which
    were already there, and the forward operation is idempotent (running
    a second time is a no-op once the rows exist), so a no-op reverse
    is safe in the rollback-the-code, leave-data-alone direction.
    """
    pass


# Raw SQL for the PK swap. We do this manually because Django's
# auto-generated AddField+AlterField sequence emits the new primary-key
# column BEFORE dropping the old one, and Postgres rejects two primary
# keys on the same table simultaneously.
_PK_SWAP_FORWARD = [
    # Drop the old PK (review_event_id was the primary key).
    "ALTER TABLE syncer_prreviewinlinecommentbackfill DROP CONSTRAINT IF EXISTS syncer_prreviewinlinecommentbackfill_pkey;",
    # review_event_id is now allowed to be NULL (dismiss events with
    # review: null produce orphan backfill rows linked only by review_node_id).
    "ALTER TABLE syncer_prreviewinlinecommentbackfill ALTER COLUMN review_event_id DROP NOT NULL;",
    # Add the new id column as bigserial (NOT NULL with auto sequence).
    # Postgres's bigserial creates a sequence with the conventional name
    # syncer_prreviewinlinecommentbackfill_id_seq, which matches what
    # Django's BigAutoField introspection expects.
    "ALTER TABLE syncer_prreviewinlinecommentbackfill ADD COLUMN id bigserial NOT NULL;",
    "ALTER TABLE syncer_prreviewinlinecommentbackfill ADD PRIMARY KEY (id);",
]

_PK_SWAP_REVERSE = [
    "ALTER TABLE syncer_prreviewinlinecommentbackfill DROP CONSTRAINT IF EXISTS syncer_prreviewinlinecommentbackfill_pkey;",
    "ALTER TABLE syncer_prreviewinlinecommentbackfill DROP COLUMN id;",
    # Restoring the old NOT NULL is best-effort: rows added during the
    # forward window with review_event_id=NULL would block this. In
    # practice the reverse path is "roll the code back, leave data
    # alone", so this branch is mostly diagnostic.
    "ALTER TABLE syncer_prreviewinlinecommentbackfill ALTER COLUMN review_event_id SET NOT NULL;",
    "ALTER TABLE syncer_prreviewinlinecommentbackfill ADD PRIMARY KEY (review_event_id);",
]


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0045_reset_timeline_backfill_for_v3_wave"),
    ]

    operations = [
        # Phase 1: PK swap. Raw SQL does the table surgery; state_operations
        # tell Django the model now has ``id`` as the PK and ``review_event``
        # as a nullable OneToOneField.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql=_PK_SWAP_FORWARD, reverse_sql=_PK_SWAP_REVERSE),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="prreviewinlinecommentbackfill",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                migrations.AlterField(
                    model_name="prreviewinlinecommentbackfill",
                    name="review_event",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inline_comment_backfill",
                        to="syncer.prtimelineevent",
                    ),
                ),
            ],
        ),
        # Phase 2: remaining schema tightenings (no PK conflict here).
        migrations.AlterField(
            model_name="prreviewinlinecomment",
            name="reply_to_node_id",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prreviewinlinecommentbackfill",
            name="review_node_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="prreviewinlinecomment",
            constraint=models.CheckConstraint(
                condition=models.Q(("review_node_id", ""), _negated=True),
                name="syncer_prric_review_node_id_not_empty",
            ),
        ),
        # Phase 3: data backfill. Order matters — synthesize parents first
        # so the inline-comment FK update can find them via
        # review_node_id == github_node_id.
        migrations.RunPython(_synthesize_dismissed_review_parents, reverse_code=_noop_reverse),
        migrations.RunPython(_link_inline_comments_to_synthesized_parents, reverse_code=_noop_reverse),
    ]
