# Generated by Django 5.2.6 on 2026-05-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0046_dismissed_review_synthesis_and_inline_schema_tightening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pullrequest',
            name='engagement_synced_at',
        ),
        migrations.RemoveField(
            model_name='syncerconvergencesnapshot',
            name='prs_engagement_incomplete',
        ),
        migrations.RemoveField(
            model_name='syncerconvergencesnapshot',
            name='prs_missing_engagement',
        ),
    ]
