# Generated by Django 5.2.6 on 2026-05-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reviewerpreference_notifications'),
        ('syncer', '0047_drop_engagement_synced_at_and_snapshot_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_name', models.CharField(max_length=64)),
                ('pr_number', models.PositiveIntegerField()),
                ('archive_path', models.CharField(max_length=512)),
                ('archive_blob_sha', models.CharField(blank=True, max_length=64, null=True)),
                ('archive_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed_transient', 'failed_transient'), ('failed_permanent', 'failed_permanent'), ('skipped', 'skipped')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_import_items', to='core.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_attempted_at'], name='syncer_archiveitem_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('archive_name', 'pr_number'), name='syncer_archiveitem_archive_pr_uniq')],
            },
        ),
    ]
