# Generated by Django 5.2.6 on 2026-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0048_archiveimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitcheckrun',
            name='archive_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitstatuscontext',
            name='archive_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prtimelineevent',
            name='archive_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='archive_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
