# Generated by Django 5.2.6 on 2026-05-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0049_commitcheckrun_archive_imported_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='archive_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='archive_failed_permanent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='archive_pending',
            field=models.IntegerField(default=0),
        ),
    ]
