# Generated by Django 5.2.6 on 2026-06-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0050_syncerconvergencesnapshot_archive_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='inconsistent_open_prs',
            field=models.IntegerField(default=0),
        ),
    ]
