# Generated by Django 5.2.6 on 2026-07-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_repository_assignment_topic_label_pattern'),
        ('syncer', '0051_syncerconvergencesnapshot_inconsistent_open_prs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archiveimportitem',
            index=models.Index(fields=['repository', 'pr_number'], name='syncer_archiveitem_repo_pr_idx'),
        ),
    ]
