# Generated by Django 5.2.6 on 2026-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncer', '0052_archiveimportitem_syncer_archiveitem_repo_pr_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncerconvergencesnapshot',
            name='archive_resync_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
