# Generated by Django 5.2.6 on 2026-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0053_syncerconvergencesnapshot_archive_resync_remaining"),
    ]

    operations = [
        migrations.AddField(
            model_name="prtimelineevent",
            name="actor_node_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prtimelineevent",
            name="actor_type",
            field=models.CharField(
                blank=True, choices=[("User", "user"), ("Bot", "bot"), ("Mannequin", "mannequin")], max_length=16, null=True
            ),
        ),
    ]
