# Generated by Django 5.2.6 on 2026-08-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syncer", "0054_prtimelineevent_actor_type_and_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="timeline_events_missing_actor_type",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncerconvergencesnapshot",
            name="timeline_events_untyped_with_login",
            field=models.IntegerField(default=0),
        ),
    ]
