name: automatically assign reviewers

on:
  schedule:
    - cron: "37 0 * * *" # At 00:37 UTC every day
  workflow_dispatch:

jobs:
  autoassign-reviewers:
    if: github.repository == 'leanprover-community/queueboard-core'
    name: assign automatically proposed reviewers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ secrets.MATHLIB_TRIAGE_APP_ID }}
          private-key: ${{ secrets.MATHLIB_TRIAGE_PRIVATE_KEY }}
          owner: leanprover-community
          repositories: mathlib4

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: master
          sparse-checkout: |
            scripts/assign_reviewers.py

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: assign reviewers
        env:
          ASSIGN_REVIEWERS_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          python3 scripts/assign_reviewers.py

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1.2.1
